<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Form_model extends CI_Model
{

    public $table = 'form';
    public $id = 'id_form';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_detail()
    {
        return $this->db->query('select * from user_akun a, form b where a.id_user = b.id_user')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    //get by id user
    function get_by_user($id)
    {
        return $this->db->query('select * from user_akun a, form b where a.id_user = b.id_user and b.id_user ='.$id)->result();
    }

    function get_by_user_div($id)
    {
        return $this->db->query('SELECT * FROM `form` JOIN `user_akun` ON `form`.`id_user` = `user_akun`.`id_user` WHERE `user_akun`.`id_division` ='.$id)->result();
    }

    //get by id user
    function get_by_user_now($id,$date)
    {
        $this->db->where('id_user', $id);
        $this->db->where('date', $date);
        $this->db->order_by('id_form','desc');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_form', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('date', $q);
	$this->db->or_like('information', $q);
	$this->db->or_like('date_needs', $q);
	$this->db->or_like('that', $q);
	$this->db->or_like('read_status_Ketua', $q);
	$this->db->or_like('read_status_TU', $q);
	$this->db->or_like('read_status_PPK', $q);
	$this->db->or_like('status_submit', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_form', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('date', $q);
	$this->db->or_like('information', $q);
	$this->db->or_like('date_needs', $q);
	$this->db->or_like('that', $q);
	$this->db->or_like('read_status_Ketua', $q);
	$this->db->or_like('read_status_TU', $q);
	$this->db->or_like('read_status_PPK', $q);
	$this->db->or_like('status_submit', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function delete_useless_form()
    {
        $this->db->where('status_submit', 0);
        $this->db->delete($this->table);
    }
    

}

/* End of file Form_model.php */
/* Location: ./application/models/Form_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-27 09:48:51 */
/* http://harviacode.com */